apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  service-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Service Monitoring",
        "panels": [
          {
            "type": "graph",
            "title": "CPU Usage",
            "targets": [
              {
                "expr": "rate(node_cpu_seconds_total[5m])",
                "legendFormat": "{{cpu}}",
                "refId": "A"
              }
            ]
          }
        ]
      }
    }
